package minesweeper;

public class Main {
    public static void main(String[] args) {
        System.out.print("""
                x........
                .x.......
                ..x......
                ...x.....
                ....x....
                .....x...
                ......x..
                .......x.
                ........x
                """);
    }
}
